spring.application.name=knowledge-preservation-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/knowledge_preservation
spring.datasource.username=postgres
spring.datasource.password=Niveabi23
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Server
# ===============================
server.port=8080
jwt.secret = mZK6Wl8Q2Z8dH4p9yN8y+R5kQpKkzP0ZVY9Hn9pU+2s=
jwt.expiration = 18000000


#===================================
# Email
#===================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nivethaselvakumar23@gmail.com
spring.mail.password=fxgj gnit yorc jxkx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


github.client-id=Ov23likmjXibVjKu30dO
github.client-secret=df1870812cfc82eef404cc4e9169b823c5b953be
github.redirect-uri=http://localhost:8080/api/github/callback

# Frontend URL
app.frontend.url=http://localhost:3000

# GitHub
github.base-url=https://github.com
github.api-url=https://api.github.com

# Jira
jira.base-url=https://your-company.atlassian.net

# Confluence
confluence.base-url=https://your-company.atlassian.net/wiki

# Outlook / Microsoft Graph
microsoft.graph-url=https://graph.microsoft.com

# Google Drive
google.api-url=https://www.googleapis.com

# GitLab
gitlab.base-url=https://gitlab.com

github.oauth.authorize-uri=${github.base-url}/login/oauth/authorize
github.oauth.token-uri=${github.base-url}/login/oauth/access_token

github.user-uri=${github.api-url}/user
